import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import * as configcat from "configcat-js-ssr";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";

import type { ApiResponse } from '@/pages/types/ApiResponse'

export const getServerSideProps = (async () => {
  // Create the ConfigCat client with your SDK Key
  const configCatClient = configcat.getClient("YOUR-SDK-KEY");

  // Get your setting value
  const randomUserFeature = await configCatClient.getValueAsync(
    "randomUserFeature",
    false
  );

  // Get a random user
  const res = await fetch("https://randomuser.me/api/");
  const data = await res.json();

  return {
    props: {
      randomUser: data.results[0],
      randomUserFeature,
    },
  };
}) satisfies GetServerSideProps<{
  randomUser: any;
  randomUserFeature: boolean;
}>;

export default function Home({
  randomUser,
  randomUserFeature,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {

  // Extract the required user details
  // const firstName = 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>Welcome to main</div>
      </main>
    </>
  );
}
